import { create } from "zustand";

export type Language = "KR" | "CN" | "EN" | "JP" | "VI";

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
}

// localStorage에서 언어 불러오기
const getStoredLanguage = (): Language => {
  if (typeof window === "undefined") return "KR";
  const stored = localStorage.getItem("userLanguage");
  // 기존 코드(ko, en 등)와 새 코드(KR, EN 등) 모두 지원
  const languageMap: Record<string, Language> = {
    ko: "KR",
    en: "EN",
    zh: "CN",
    ja: "JP",
    vi: "VI",
    KR: "KR",
    EN: "EN",
    CN: "CN",
    JP: "JP",
    VI: "VI",
  };
  if (stored && languageMap[stored]) {
    return languageMap[stored];
  }
  return "KR";
};

export const useLanguage = create<LanguageState>((set) => ({
  language: getStoredLanguage(),
  setLanguage: (lang) => {
    localStorage.setItem("userLanguage", lang);
    set({ language: lang });
  },
}));

// 언어별 텍스트 정의
export const translations = {
  KR: {
    intro: [
      "1단계 : 알아듣지 못하는 강의를 업로드하세요",
      "2단계 : 모국어로 번역된 수업 요약본을 보고 학습해보세요",
      "3단계 : 생성된 문제를 보고 학습해보세요",
      "4단계 : 해당 수업의 심화를 다룬 내용들도 학습해보세요",
      "Orbit과 함께 학습을 해볼까요?",
    ],
    title: "Orbit",
    signup: {
      title: "Orbit AI 시작하기",
      name: "이름",
      namePlaceholder: "이름을 입력하세요",
      useridPlaceholder: "사용자 ID를 입력하세요",
      email: "이메일",
      emailPlaceholder: "이메일을 입력하세요",
      password: "비밀번호",
      passwordPlaceholder: "비밀번호를 입력하세요",
      confirmPassword: "비밀번호 확인",
      confirmPasswordPlaceholder: "비밀번호를 다시 입력하세요",
      language: "언어",
      languagePlaceholder: "언어를 선택하세요",
      signupButton: "회원가입",
      signupLoading: "가입 중...",
      loginLink: "이미 계정이 있으신가요?",
      loginButton: "로그인",
      errors: {
        allFieldsRequired: "모든 필드를 입력해주세요",
        passwordMismatch: "비밀번호가 일치하지 않습니다",
        passwordTooShort: "비밀번호는 8자 이상이어야 합니다",
        signupFailed: "회원가입에 실패했습니다",
      },
    },
    login: {
      title: "Orbit AI 시작하기",
      userid: "사용자 ID",
      useridPlaceholder: "사용자 ID를 입력하세요",
      password: "비밀번호",
      passwordPlaceholder: "비밀번호를 입력하세요",
      loginButton: "로그인",
      loginLoading: "로그인 중...",
      signupButton: "회원가입",
      errors: {
        loginFailed: "로그인에 실패했습니다",
      },
    },
    home: {
      greeting: "안녕하세요!",
      welcomeMessage: "홍길동 교수님을 도와드릴 AI Tutor예요",
      homeTitle: "홈",
      uploadFile: "파일 업로드",
      emptyState: {
        title: "강의 영상을 업로드해보세요",
        description:
          "파일을 드래그하거나 클릭하여 강의 영상을 업로드할 수 있어요!",
      },
      sidebar: {
        home: "홈",
        courses: "강의 과목",
        schoolTips: "학교 꿀팁",
        logout: "로그아웃",
      },
      content: {
        translation: "번역본",
        summary: "요약",
        quiz: "퀴즈",
        advanced: "리뷰",
        number: "번호",
        back: "뒤로가기",
        viewDetails: "강의 상세 보기",
        summaryContent: "강의 녹음본에 대한 요약본이 여기에 표시됩니다.",
        quizContent: "퀴즈 내용이 여기에 표시됩니다.",
        advancedContent: "강의 리뷰가 여기에 표시됩니다.",
        quizNumber: "퀴즈 번호",
        questionCount: "문제 개수",
        difficulty: "난이도",
        createdAt: "생성일",
        download: "다운로드",
        delete: "삭제",
        createQuiz: "퀴즈 생성",
        quizGenerationComplete: "퀴즈 생성 완료",
        select: "선택",
        problem: "문제",
        answer: "답",
        questionType: "문제 유형",
        generatePDF: "PDF 생성",
        showAnswer: "답 보기",
        hideAnswer: "답 숨기기",
        maxQuestions: "최대",
        questions: "개",
        difficultyHigh: "상",
        difficultyMedium: "중",
        difficultyLow: "하",
        questionTypeShortAnswer: "단답형",
        questionTypeTrueFalse: "o.x",
        questionTypeMultipleChoice: "객관식",
        generateQuiz: "문제지 생성",
        quizGenerating: {
          analyzing: "강의 내용을 분석하고 있습니다...",
          creating: "문제를 생성하고 있습니다...",
          adjusting: "난이도를 조정하고 있습니다...",
          reviewing: "최종 검토 중입니다...",
          waitMessage:
            "잠시만 기다려주세요. AI가 최적의 문제를 생성하고 있습니다.",
        },
        review: {
          create: "리뷰 생성",
          creating: "리뷰 생성 중...",
          generating: "리뷰를 생성하는 중...",
          success: "리뷰가 생성되었습니다!",
          error: "리뷰 생성에 실패했습니다.",
          noLectureData: "강의 정보를 불러올 수 없습니다.",
          createInDetailPage:
            "리뷰 기능은 강의 상세 페이지에서 생성할 수 있습니다.",
        },
      },
      uploadModal: {
        fileInfo: "파일 정보",
        classTitle: "수업 제목 입력",
        cancel: "취소",
        confirm: "확인",
      },
      uploadArea: {
        title: "파일을 첨부해 주세요!",
        description: "파일을 드래그하거나 클릭하여 업로드하세요",
        folderRequired:
          "⚠️ 먼저 사이드바에서 폴더를 선택하거나 새 폴더를 만들어주세요",
        createFolder: "폴더 만들기",
      },
      upload: {
        uploading: "파일을 업로드하고 있습니다...",
        processing: "파일을 처리하고 있습니다...",
        translating: "번역을 진행하고 있습니다...",
        completing: "완료 중입니다...",
        waitMessage: "잠시만 기다려주세요. 강의 파일을 처리하고 있습니다.",
      },
      folder: {
        noFolders: "폴더가 없습니다",
        createFolder: "새 폴더 만들기",
        folderName: "폴더 이름",
        folderNamePlaceholder: "폴더 이름을 입력하세요",
        creating: "생성 중...",
        create: "생성",
        selectFolderFirst:
          "먼저 사이드바에서 폴더를 선택하거나 새 폴더를 생성해주세요",
      },
    },
    userMenu: {
      editProfile: "회원 수정",
      deleteAccount: "회원 삭제",
      deleteAccountModal: {
        title: "회원 삭제",
        message: "정말 회원을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.",
        cancel: "취소",
        confirm: "삭제",
      },
    },
  },
  EN: {
    intro: [
      "Step 1: Upload lectures you don't understand",
      "Step 2: Review and learn from the translated lecture summary in your native language",
      "Step 3: Review and learn from the generated problems",
      "Step 4: Try learning from the advanced content covering the in-depth aspects of the lecture",
      "Shall we learn together with Orbit?",
    ],
    title: "Orbit",
    signup: {
      title: "Get Started with Orbit AI",
      name: "Name",
      namePlaceholder: "Enter your name",
      useridPlaceholder: "Enter your user ID",
      email: "Email",
      emailPlaceholder: "Enter your email",
      password: "Password",
      passwordPlaceholder: "Enter your password",
      confirmPassword: "Confirm Password",
      confirmPasswordPlaceholder: "Re-enter your password",
      language: "Language",
      languagePlaceholder: "Select a language",
      signupButton: "Sign Up",
      signupLoading: "Signing up...",
      loginLink: "Already have an account?",
      loginButton: "Log In",
      errors: {
        allFieldsRequired: "Please fill in all fields",
        passwordMismatch: "Passwords do not match",
        passwordTooShort: "Password must be at least 8 characters",
        signupFailed: "Sign up failed",
      },
    },
    login: {
      title: "Get Started with Orbit AI",
      userid: "User ID",
      useridPlaceholder: "Enter your user ID",
      password: "Password",
      passwordPlaceholder: "Enter your password",
      loginButton: "Log In",
      loginLoading: "Logging in...",
      signupButton: "Sign Up",
      errors: {
        loginFailed: "Login failed",
      },
    },
    home: {
      greeting: "Hello!",
      welcomeMessage: "I am an AI Tutor to help Professor Hong Gil-dong",
      homeTitle: "Home",
      uploadFile: "Upload File",
      emptyState: {
        title: "Upload your lecture video",
        description:
          "Drag and drop files or click to upload your lecture video!",
      },
      sidebar: {
        home: "Home",
        courses: "Course Subjects",
        schoolTips: "School Tips",
        logout: "Logout",
      },
      content: {
        translation: "Translation",
        summary: "Summary",
        quiz: "Quiz",
        advanced: "Review",
        number: "Number",
        back: "Back",
        viewDetails: "View Course Details",
        summaryContent:
          "Summary of the lecture recording will be displayed here.",
        quizContent: "Quiz content will be displayed here.",
        advancedContent: "Lecture review will be displayed here.",
        quizNumber: "Quiz Number",
        questionCount: "Question Count",
        difficulty: "Difficulty",
        createdAt: "Created At",
        download: "Download",
        delete: "Delete",
        createQuiz: "Create Quiz",
        quizGenerationComplete: "Quiz Generation Complete",
        select: "Select",
        problem: "Problem",
        answer: "Answer",
        questionType: "Question Type",
        generatePDF: "Generate PDF",
        showAnswer: "Show Answer",
        hideAnswer: "Hide Answer",
        maxQuestions: "Max",
        questions: "questions",
        difficultyHigh: "High",
        difficultyMedium: "Medium",
        difficultyLow: "Low",
        questionTypeShortAnswer: "Short Answer",
        questionTypeTrueFalse: "True/False",
        questionTypeMultipleChoice: "Multiple Choice",
        generateQuiz: "Generate Quiz",
        quizGenerating: {
          analyzing: "Analyzing lecture content...",
          creating: "Creating questions...",
          adjusting: "Adjusting difficulty...",
          reviewing: "Final review in progress...",
          waitMessage: "Please wait. AI is generating optimal questions.",
        },
        review: {
          create: "Create Review",
          creating: "Creating Review...",
          generating: "Generating review...",
          success: "Review has been created!",
          error: "Failed to create review.",
          noLectureData: "Unable to load lecture information.",
          createInDetailPage:
            "Review feature can be created in the lecture detail page.",
        },
      },
      uploadModal: {
        fileInfo: "File Information",
        classTitle: "Enter Class Title",
        cancel: "Cancel",
        confirm: "Confirm",
      },
      uploadArea: {
        title: "Please attach a file!",
        description: "Drag or click to upload files",
        folderRequired:
          "⚠️ Please select a folder from the sidebar or create a new folder first",
        createFolder: "Create Folder",
      },
      upload: {
        uploading: "Uploading file...",
        processing: "Processing file...",
        translating: "Translating...",
        completing: "Completing...",
        waitMessage: "Please wait. Processing lecture file.",
      },
      folder: {
        noFolders: "No folders",
        createFolder: "Create New Folder",
        folderName: "Folder Name",
        folderNamePlaceholder: "Enter folder name",
        creating: "Creating...",
        create: "Create",
        selectFolderFirst:
          "Please select a folder from the sidebar or create a new folder first",
      },
    },
    userMenu: {
      editProfile: "Edit Profile",
      deleteAccount: "Delete Account",
      deleteAccountModal: {
        title: "Delete Account",
        message:
          "Are you sure you want to delete your account? This action cannot be undone.",
        cancel: "Cancel",
        confirm: "Delete",
      },
    },
  },
  CN: {
    intro: [
      "第1步：上传您听不懂的讲座",
      "第2步：查看并学习用您的母语翻译的课程摘要",
      "第3步：查看并学习生成的问题",
      "第4步：也尝试学习涵盖该课程深入内容的进阶内容",
      "让我们一起与Orbit一起学习吧？",
    ],
    title: "Orbit",
    signup: {
      title: "开始使用Orbit AI",
      name: "姓名",
      namePlaceholder: "请输入您的姓名",
      useridPlaceholder: "请输入您的用户ID",
      email: "电子邮件",
      emailPlaceholder: "请输入您的电子邮件",
      password: "密码",
      passwordPlaceholder: "请输入您的密码",
      confirmPassword: "确认密码",
      confirmPasswordPlaceholder: "请再次输入您的密码",
      language: "语言",
      languagePlaceholder: "选择语言",
      signupButton: "注册",
      signupLoading: "注册中...",
      loginLink: "已有账户？",
      loginButton: "登录",
      errors: {
        allFieldsRequired: "请填写所有字段",
        passwordMismatch: "密码不匹配",
        passwordTooShort: "密码必须至少8个字符",
        signupFailed: "注册失败",
      },
    },
    login: {
      title: "开始使用Orbit AI",
      userid: "用户ID",
      useridPlaceholder: "请输入您的用户ID",
      password: "密码",
      passwordPlaceholder: "请输入您的密码",
      loginButton: "登录",
      loginLoading: "登录中...",
      signupButton: "注册",
      errors: {
        loginFailed: "登录失败",
      },
    },
    home: {
      greeting: "你好！",
      welcomeMessage: "我是帮助洪吉童教授的AI Tutor",
      homeTitle: "首页",
      uploadFile: "上传文件",
      emptyState: {
        title: "上传您的讲座视频",
        description: "拖放文件或点击上传您的讲座视频！",
      },
      sidebar: {
        home: "首页",
        courses: "课程科目",
        schoolTips: "学校小贴士",
        logout: "登出",
      },
      content: {
        translation: "翻译本",
        summary: "摘要",
        quiz: "测验",
        advanced: "评论",
        number: "编号",
        back: "返回",
        viewDetails: "查看课程详情",
        summaryContent: "讲座录音的摘要将显示在这里。",
        quizContent: "测验内容将显示在这里。",
        advancedContent: "讲座评论将显示在这里。",
        quizNumber: "测验编号",
        questionCount: "问题数量",
        difficulty: "难度",
        createdAt: "创建日期",
        download: "下载",
        delete: "删除",
        createQuiz: "创建测验",
        quizGenerationComplete: "测验生成完成",
        select: "选择",
        problem: "问题",
        answer: "答案",
        questionType: "问题类型",
        generatePDF: "生成PDF",
        showAnswer: "显示答案",
        hideAnswer: "隐藏答案",
        maxQuestions: "最多",
        questions: "题",
        difficultyHigh: "高",
        difficultyMedium: "中",
        difficultyLow: "低",
        questionTypeShortAnswer: "简答题",
        questionTypeTrueFalse: "判断题",
        questionTypeMultipleChoice: "选择题",
        generateQuiz: "生成试卷",
        quizGenerating: {
          analyzing: "正在分析讲座内容...",
          creating: "正在创建问题...",
          adjusting: "正在调整难度...",
          reviewing: "正在进行最终审查...",
          waitMessage: "请稍候。AI正在生成最佳问题。",
        },
        review: {
          create: "创建评论",
          creating: "正在创建评论...",
          generating: "正在生成评论...",
          success: "评论已创建！",
          error: "创建评论失败。",
          noLectureData: "无法加载讲座信息。",
          createInDetailPage: "评论功能可以在讲座详情页面中创建。",
        },
      },
      uploadModal: {
        fileInfo: "文件信息",
        classTitle: "输入课程标题",
        cancel: "取消",
        confirm: "确认",
      },
      uploadArea: {
        title: "请附加文件！",
        description: "拖放或点击上传文件",
        folderRequired: "⚠️ 请先从侧边栏选择文件夹或创建新文件夹",
        createFolder: "创建文件夹",
      },
      upload: {
        uploading: "正在上传文件...",
        processing: "正在处理文件...",
        translating: "正在翻译...",
        completing: "正在完成...",
        waitMessage: "请稍候。正在处理讲座文件。",
      },
      folder: {
        noFolders: "没有文件夹",
        createFolder: "创建新文件夹",
        folderName: "文件夹名称",
        folderNamePlaceholder: "请输入文件夹名称",
        creating: "创建中...",
        create: "创建",
        selectFolderFirst: "请先从侧边栏选择文件夹或创建新文件夹",
      },
    },
    userMenu: {
      editProfile: "编辑资料",
      deleteAccount: "删除账户",
      deleteAccountModal: {
        title: "删除账户",
        message: "您确定要删除您的账户吗？此操作无法撤销。",
        cancel: "取消",
        confirm: "删除",
      },
    },
  },
  JP: {
    intro: [
      "ステップ1：理解できない講義をアップロードしてください",
      "ステップ2：母国語に翻訳された授業の要約を見て学習してください",
      "ステップ3：生成された問題を見て学習してください",
      "ステップ4：その授業の深化を扱った内容も学習してみてください",
      "Orbitと一緒に学習してみませんか？",
    ],
    title: "Orbit",
    signup: {
      title: "Orbit AIを始める",
      name: "名前",
      namePlaceholder: "お名前を入力してください",
      useridPlaceholder: "ユーザーIDを入力してください",
      email: "メールアドレス",
      emailPlaceholder: "メールアドレスを入力してください",
      password: "パスワード",
      passwordPlaceholder: "パスワードを入力してください",
      confirmPassword: "パスワード確認",
      confirmPasswordPlaceholder: "パスワードを再度入力してください",
      language: "言語",
      languagePlaceholder: "言語を選択してください",
      signupButton: "会員登録",
      signupLoading: "登録中...",
      loginLink: "すでにアカウントをお持ちですか？",
      loginButton: "ログイン",
      errors: {
        allFieldsRequired: "すべてのフィールドを入力してください",
        passwordMismatch: "パスワードが一致しません",
        passwordTooShort: "パスワードは8文字以上である必要があります",
        signupFailed: "会員登録に失敗しました",
      },
    },
    login: {
      title: "Orbit AIを始める",
      userid: "ユーザーID",
      useridPlaceholder: "ユーザーIDを入力してください",
      password: "パスワード",
      passwordPlaceholder: "パスワードを入力してください",
      loginButton: "ログイン",
      loginLoading: "ログイン中...",
      signupButton: "会員登録",
      errors: {
        loginFailed: "ログインに失敗しました",
      },
    },
    home: {
      greeting: "こんにちは！",
      welcomeMessage: "洪吉童教授をお手伝いするAI Tutorです",
      homeTitle: "ホーム",
      uploadFile: "ファイルをアップロード",
      emptyState: {
        title: "講義動画をアップロードしてください",
        description:
          "ファイルをドラッグ＆ドロップするか、クリックして講義動画をアップロードできます！",
      },
      sidebar: {
        home: "ホーム",
        courses: "講義科目",
        schoolTips: "学校のコツ",
        logout: "ログアウト",
      },
      content: {
        translation: "翻訳版",
        summary: "要約",
        quiz: "クイズ",
        advanced: "レビュー",
        number: "番号",
        back: "戻る",
        viewDetails: "講義詳細を見る",
        summaryContent: "講義録音の要約がここに表示されます。",
        quizContent: "クイズの内容がここに表示されます。",
        advancedContent: "講義レビューがここに表示されます。",
        quizNumber: "クイズ番号",
        questionCount: "問題数",
        difficulty: "難易度",
        createdAt: "作成日",
        download: "ダウンロード",
        delete: "削除",
        createQuiz: "クイズ作成",
        quizGenerationComplete: "クイズ生成完了",
        select: "選択",
        problem: "問題",
        answer: "答え",
        questionType: "問題タイプ",
        generatePDF: "PDF生成",
        showAnswer: "答えを表示",
        hideAnswer: "答えを非表示",
        maxQuestions: "最大",
        questions: "問",
        difficultyHigh: "高",
        difficultyMedium: "中",
        difficultyLow: "低",
        questionTypeShortAnswer: "記述式",
        questionTypeTrueFalse: "○×",
        questionTypeMultipleChoice: "選択式",
        generateQuiz: "問題用紙生成",
        quizGenerating: {
          analyzing: "講義内容を分析しています...",
          creating: "問題を作成しています...",
          adjusting: "難易度を調整しています...",
          reviewing: "最終確認中です...",
          waitMessage: "少々お待ちください。AIが最適な問題を生成しています。",
        },
        review: {
          create: "レビュー作成",
          creating: "レビュー作成中...",
          generating: "レビューを生成しています...",
          success: "レビューが作成されました！",
          error: "レビューの作成に失敗しました。",
          noLectureData: "講義情報を読み込めません。",
          createInDetailPage: "レビュー機能は講義詳細ページで作成できます。",
        },
      },
      uploadModal: {
        fileInfo: "ファイル情報",
        classTitle: "授業タイトル入力",
        cancel: "キャンセル",
        confirm: "確認",
      },
      uploadArea: {
        title: "ファイルを添付してください！",
        description:
          "ファイルをドラッグまたはクリックしてアップロードしてください",
        folderRequired:
          "⚠️ まずサイドバーからフォルダを選択するか、新しいフォルダを作成してください",
        createFolder: "フォルダを作成",
      },
      upload: {
        uploading: "ファイルをアップロードしています...",
        processing: "ファイルを処理しています...",
        translating: "翻訳を進めています...",
        completing: "完了中です...",
        waitMessage: "少々お待ちください。講義ファイルを処理しています。",
      },
      folder: {
        noFolders: "フォルダがありません",
        createFolder: "新しいフォルダを作成",
        folderName: "フォルダ名",
        folderNamePlaceholder: "フォルダ名を入力してください",
        creating: "作成中...",
        create: "作成",
        selectFolderFirst:
          "まずサイドバーからフォルダを選択するか、新しいフォルダを作成してください",
      },
    },
    userMenu: {
      editProfile: "プロフィール編集",
      deleteAccount: "アカウント削除",
      deleteAccountModal: {
        title: "アカウント削除",
        message: "本当にアカウントを削除しますか？この操作は元に戻せません。",
        cancel: "キャンセル",
        confirm: "削除",
      },
    },
  },
  VI: {
    intro: [
      "Bước 1: Tải lên các bài giảng bạn không hiểu",
      "Bước 2: Xem và học từ bản tóm tắt bài giảng được dịch sang ngôn ngữ mẹ đẻ của bạn",
      "Bước 3: Xem và học từ các câu hỏi được tạo ra",
      "Bước 4: Hãy thử học từ nội dung nâng cao bao gồm các khía cạnh sâu sắc của bài giảng",
      "Chúng ta hãy cùng học với Orbit nhé?",
    ],
    title: "Orbit",
    signup: {
      title: "Bắt đầu với Orbit AI",
      name: "Tên",
      namePlaceholder: "Nhập tên của bạn",
      useridPlaceholder: "Nhập ID người dùng của bạn",
      email: "Email",
      emailPlaceholder: "Nhập email của bạn",
      password: "Mật khẩu",
      passwordPlaceholder: "Nhập mật khẩu của bạn",
      confirmPassword: "Xác nhận mật khẩu",
      confirmPasswordPlaceholder: "Nhập lại mật khẩu của bạn",
      language: "Ngôn ngữ",
      languagePlaceholder: "Chọn ngôn ngữ",
      signupButton: "Đăng ký",
      signupLoading: "Đang đăng ký...",
      loginLink: "Đã có tài khoản?",
      loginButton: "Đăng nhập",
      errors: {
        allFieldsRequired: "Vui lòng điền tất cả các trường",
        passwordMismatch: "Mật khẩu không khớp",
        passwordTooShort: "Mật khẩu phải có ít nhất 8 ký tự",
        signupFailed: "Đăng ký thất bại",
      },
    },
    login: {
      title: "Bắt đầu với Orbit AI",
      userid: "ID người dùng",
      useridPlaceholder: "Nhập ID người dùng của bạn",
      password: "Mật khẩu",
      passwordPlaceholder: "Nhập mật khẩu của bạn",
      loginButton: "Đăng nhập",
      loginLoading: "Đang đăng nhập...",
      signupButton: "Đăng ký",
      errors: {
        loginFailed: "Đăng nhập thất bại",
      },
    },
    home: {
      greeting: "Xin chào!",
      welcomeMessage: "Tôi là AI Tutor để giúp Giáo sư Hong Gil-dong",
      homeTitle: "Trang chủ",
      uploadFile: "Tải lên tệp",
      emptyState: {
        title: "Tải lên video bài giảng của bạn",
        description:
          "Kéo thả tệp hoặc nhấp để tải lên video bài giảng của bạn!",
      },
      sidebar: {
        home: "Trang chủ",
        courses: "Môn học",
        schoolTips: "Mẹo học tập",
        logout: "Đăng xuất",
      },
      content: {
        translation: "Bản dịch",
        summary: "Tóm tắt",
        quiz: "Câu đố",
        advanced: "Đánh giá",
        number: "Số",
        back: "Quay lại",
        viewDetails: "Xem chi tiết khóa học",
        summaryContent: "Tóm tắt của bản ghi bài giảng sẽ được hiển thị ở đây.",
        quizContent: "Nội dung câu đố sẽ được hiển thị ở đây.",
        advancedContent: "Đánh giá bài giảng sẽ được hiển thị ở đây.",
        quizNumber: "Số câu đố",
        questionCount: "Số câu hỏi",
        difficulty: "Độ khó",
        createdAt: "Ngày tạo",
        download: "Tải xuống",
        delete: "Xóa",
        createQuiz: "Tạo câu đố",
        quizGenerationComplete: "Hoàn thành tạo câu đố",
        select: "Chọn",
        problem: "Câu hỏi",
        answer: "Đáp án",
        questionType: "Loại câu hỏi",
        generatePDF: "Tạo PDF",
        showAnswer: "Hiển thị đáp án",
        hideAnswer: "Ẩn đáp án",
        maxQuestions: "Tối đa",
        questions: "câu",
        difficultyHigh: "Cao",
        difficultyMedium: "Trung bình",
        difficultyLow: "Thấp",
        questionTypeShortAnswer: "Tự luận",
        questionTypeTrueFalse: "Đúng/Sai",
        questionTypeMultipleChoice: "Trắc nghiệm",
        generateQuiz: "Tạo đề thi",
        quizGenerating: {
          analyzing: "Đang phân tích nội dung bài giảng...",
          creating: "Đang tạo câu hỏi...",
          adjusting: "Đang điều chỉnh độ khó...",
          reviewing: "Đang xem xét cuối cùng...",
          waitMessage: "Vui lòng đợi. AI đang tạo các câu hỏi tối ưu.",
        },
        review: {
          create: "Tạo đánh giá",
          creating: "Đang tạo đánh giá...",
          generating: "Đang tạo đánh giá...",
          success: "Đánh giá đã được tạo!",
          error: "Không thể tạo đánh giá.",
          noLectureData: "Không thể tải thông tin bài giảng.",
          createInDetailPage:
            "Tính năng đánh giá có thể được tạo trong trang chi tiết bài giảng.",
        },
      },
      uploadModal: {
        fileInfo: "Thông tin tệp",
        classTitle: "Nhập tiêu đề lớp học",
        cancel: "Hủy",
        confirm: "Xác nhận",
      },
      uploadArea: {
        title: "Vui lòng đính kèm tệp!",
        description: "Kéo thả hoặc nhấp để tải tệp lên",
        folderRequired:
          "⚠️ Vui lòng chọn thư mục từ thanh bên hoặc tạo thư mục mới trước",
        createFolder: "Tạo thư mục",
      },
      upload: {
        uploading: "Đang tải tệp lên...",
        processing: "Đang xử lý tệp...",
        translating: "Đang dịch...",
        completing: "Đang hoàn thành...",
        waitMessage: "Vui lòng đợi. Đang xử lý tệp bài giảng.",
      },
      folder: {
        noFolders: "Không có thư mục",
        createFolder: "Tạo thư mục mới",
        folderName: "Tên thư mục",
        folderNamePlaceholder: "Nhập tên thư mục",
        creating: "Đang tạo...",
        create: "Tạo",
        selectFolderFirst:
          "Vui lòng chọn thư mục từ thanh bên hoặc tạo thư mục mới trước",
      },
    },
    userMenu: {
      editProfile: "Chỉnh sửa hồ sơ",
      deleteAccount: "Xóa tài khoản",
      deleteAccountModal: {
        title: "Xóa tài khoản",
        message:
          "Bạn có chắc chắn muốn xóa tài khoản của mình không? Hành động này không thể hoàn tác.",
        cancel: "Hủy",
        confirm: "Xóa",
      },
    },
  },
};
