import { create } from "zustand";

export type Language = "ko" | "en" | "zh" | "ja" | "vi" | "mn";

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
}

// localStorage에서 언어 불러오기
const getStoredLanguage = (): Language => {
  if (typeof window === "undefined") return "ko";
  const stored = localStorage.getItem("userLanguage");
  if (stored && ["ko", "en", "zh", "ja", "vi", "mn"].includes(stored)) {
    return stored as Language;
  }
  return "ko";
};

export const useLanguage = create<LanguageState>((set) => ({
  language: getStoredLanguage(),
  setLanguage: (lang) => {
    localStorage.setItem("userLanguage", lang);
    set({ language: lang });
  },
}));

// 언어별 텍스트 정의
export const translations = {
  ko: {
    intro: [
      "1단계 : 알아듣지 못하는 강의를 업로드하세요",
      "2단계 : 모국어로 번역된 수업 요약본을 보고 학습",
      "3단계 : 생성된 문제를 보고 학습해보세요",
      "4단계 : 해당 수업의 심화를 다룬 내용들도 학습해보세요",
      "Orbit과 함께 학습을 해볼까요?",
    ],
    title: "Orbit",
    signup: {
      title: "Orbit AI 시작하기",
      name: "이름",
      namePlaceholder: "이름을 입력하세요",
      email: "이메일",
      emailPlaceholder: "이메일을 입력하세요",
      password: "비밀번호",
      passwordPlaceholder: "비밀번호를 입력하세요",
      confirmPassword: "비밀번호 확인",
      confirmPasswordPlaceholder: "비밀번호를 다시 입력하세요",
      language: "언어",
      languagePlaceholder: "언어를 선택하세요",
      signupButton: "회원가입",
      signupLoading: "가입 중...",
      loginLink: "이미 계정이 있으신가요?",
      loginButton: "로그인",
      errors: {
        allFieldsRequired: "모든 필드를 입력해주세요",
        passwordMismatch: "비밀번호가 일치하지 않습니다",
        passwordTooShort: "비밀번호는 8자 이상이어야 합니다",
        signupFailed: "회원가입에 실패했습니다",
      },
    },
    home: {
      greeting: "안녕하세요!",
      welcomeMessage: "홍길동 교수님을 도와드릴 AI Tutor예요",
      homeTitle: "홈",
      uploadFile: "파일 업로드",
      emptyState: {
        title: "강의 영상을 업로드해보세요",
        description:
          "파일을 드래그하거나 클릭하여 강의 영상을 업로드할 수 있어요!",
      },
      sidebar: {
        home: "홈",
        courses: "강의 과목",
        logout: "로그아웃",
      },
      content: {
        translation: "번역본",
        summary: "요약",
        quiz: "퀴즈",
        advanced: "심화",
        number: "번호",
        back: "뒤로가기",
        summaryContent: "강의 녹음본에 대한 요약본이 여기에 표시됩니다.",
        quizContent: "퀴즈 내용이 여기에 표시됩니다.",
        advancedContent: "심화 내용이 여기에 표시됩니다.",
        quizNumber: "퀴즈 번호",
        questionCount: "문제 개수",
        difficulty: "난이도",
        createdAt: "생성일",
        download: "다운로드",
        delete: "삭제",
        createQuiz: "퀴즈 생성",
        quizGenerationComplete: "퀴즈 생성 완료",
        select: "선택",
        problem: "문제",
        answer: "답",
        questionType: "문제 유형",
        generatePDF: "PDF 생성",
        showAnswer: "답 보기",
        hideAnswer: "답 숨기기",
        maxQuestions: "최대",
        questions: "개",
        difficultyHigh: "상",
        difficultyMedium: "중",
        difficultyLow: "하",
        questionTypeShortAnswer: "단답형",
        questionTypeTrueFalse: "o.x",
        questionTypeMultipleChoice: "객관식",
        generateQuiz: "문제지 생성",
      },
      uploadModal: {
        fileInfo: "파일 정보",
        classTitle: "수업 제목 입력",
        cancel: "취소",
        confirm: "확인",
      },
    },
  },
  en: {
    intro: [
      "Step 1: Upload lectures you don't understand",
      "Step 2: Review and learn from the translated lecture summary in your native language",
      "Step 3: Review and learn from the generated problems",
      "Step 4: Try learning from the advanced content covering the in-depth aspects of the lecture",
      "Shall we learn together with Orbit?",
    ],
    title: "Orbit",
    signup: {
      title: "Get Started with Orbit AI",
      name: "Name",
      namePlaceholder: "Enter your name",
      email: "Email",
      emailPlaceholder: "Enter your email",
      password: "Password",
      passwordPlaceholder: "Enter your password",
      confirmPassword: "Confirm Password",
      confirmPasswordPlaceholder: "Re-enter your password",
      language: "Language",
      languagePlaceholder: "Select a language",
      signupButton: "Sign Up",
      signupLoading: "Signing up...",
      loginLink: "Already have an account?",
      loginButton: "Log In",
      errors: {
        allFieldsRequired: "Please fill in all fields",
        passwordMismatch: "Passwords do not match",
        passwordTooShort: "Password must be at least 8 characters",
        signupFailed: "Sign up failed",
      },
    },
    home: {
      greeting: "Hello!",
      welcomeMessage: "I am an AI Tutor to help Professor Hong Gil-dong",
      homeTitle: "Home",
      uploadFile: "Upload File",
      emptyState: {
        title: "Upload your lecture video",
        description:
          "Drag and drop files or click to upload your lecture video!",
      },
      sidebar: {
        home: "Home",
        courses: "Course Subjects",
        logout: "Logout",
      },
      content: {
        translation: "Translation",
        summary: "Summary",
        quiz: "Quiz",
        advanced: "Advanced",
        number: "Number",
        back: "Back",
        summaryContent:
          "Summary of the lecture recording will be displayed here.",
        quizContent: "Quiz content will be displayed here.",
        advancedContent: "Advanced content will be displayed here.",
        quizNumber: "Quiz Number",
        questionCount: "Question Count",
        difficulty: "Difficulty",
        createdAt: "Created At",
        download: "Download",
        delete: "Delete",
        createQuiz: "Create Quiz",
        quizGenerationComplete: "Quiz Generation Complete",
        select: "Select",
        problem: "Problem",
        answer: "Answer",
        questionType: "Question Type",
        generatePDF: "Generate PDF",
        showAnswer: "Show Answer",
        hideAnswer: "Hide Answer",
        maxQuestions: "Max",
        questions: "questions",
        difficultyHigh: "High",
        difficultyMedium: "Medium",
        difficultyLow: "Low",
        questionTypeShortAnswer: "Short Answer",
        questionTypeTrueFalse: "True/False",
        questionTypeMultipleChoice: "Multiple Choice",
        generateQuiz: "Generate Quiz",
      },
      uploadModal: {
        fileInfo: "File Information",
        classTitle: "Enter Class Title",
        cancel: "Cancel",
        confirm: "Confirm",
      },
    },
  },
  zh: {
    intro: [
      "第1步：上传您听不懂的讲座",
      "第2步：查看并学习用您的母语翻译的课程摘要",
      "第3步：查看并学习生成的问题",
      "第4步：也尝试学习涵盖该课程深入内容的进阶内容",
      "让我们一起与Orbit一起学习吧？",
    ],
    title: "Orbit",
    signup: {
      title: "开始使用Orbit AI",
      name: "姓名",
      namePlaceholder: "请输入您的姓名",
      email: "电子邮件",
      emailPlaceholder: "请输入您的电子邮件",
      password: "密码",
      passwordPlaceholder: "请输入您的密码",
      confirmPassword: "确认密码",
      confirmPasswordPlaceholder: "请再次输入您的密码",
      language: "语言",
      languagePlaceholder: "选择语言",
      signupButton: "注册",
      signupLoading: "注册中...",
      loginLink: "已有账户？",
      loginButton: "登录",
      errors: {
        allFieldsRequired: "请填写所有字段",
        passwordMismatch: "密码不匹配",
        passwordTooShort: "密码必须至少8个字符",
        signupFailed: "注册失败",
      },
    },
    home: {
      greeting: "你好！",
      welcomeMessage: "我是帮助洪吉童教授的AI Tutor",
      homeTitle: "首页",
      uploadFile: "上传文件",
      emptyState: {
        title: "上传您的讲座视频",
        description: "拖放文件或点击上传您的讲座视频！",
      },
      sidebar: {
        home: "首页",
        courses: "课程科目",
        logout: "登出",
      },
      content: {
        translation: "翻译本",
        summary: "摘要",
        quiz: "测验",
        advanced: "深化",
        number: "编号",
        back: "返回",
        summaryContent: "讲座录音的摘要将显示在这里。",
        quizContent: "测验内容将显示在这里。",
        advancedContent: "深化内容将显示在这里。",
        quizNumber: "测验编号",
        questionCount: "问题数量",
        difficulty: "难度",
        createdAt: "创建日期",
        download: "下载",
        delete: "删除",
        createQuiz: "创建测验",
        quizGenerationComplete: "测验生成完成",
        select: "选择",
        problem: "问题",
        answer: "答案",
        questionType: "问题类型",
        generatePDF: "生成PDF",
        showAnswer: "显示答案",
        hideAnswer: "隐藏答案",
        maxQuestions: "最多",
        questions: "题",
        difficultyHigh: "高",
        difficultyMedium: "中",
        difficultyLow: "低",
        questionTypeShortAnswer: "简答题",
        questionTypeTrueFalse: "判断题",
        questionTypeMultipleChoice: "选择题",
        generateQuiz: "生成试卷",
      },
      uploadModal: {
        fileInfo: "文件信息",
        classTitle: "输入课程标题",
        cancel: "取消",
        confirm: "确认",
      },
    },
  },
  ja: {
    intro: [
      "ステップ1：理解できない講義をアップロードしてください",
      "ステップ2：母国語に翻訳された授業の要約を見て学習してください",
      "ステップ3：生成された問題を見て学習してください",
      "ステップ4：その授業の深化を扱った内容も学習してみてください",
      "Orbitと一緒に学習してみませんか？",
    ],
    title: "Orbit",
    signup: {
      title: "Orbit AIを始める",
      name: "名前",
      namePlaceholder: "お名前を入力してください",
      email: "メールアドレス",
      emailPlaceholder: "メールアドレスを入力してください",
      password: "パスワード",
      passwordPlaceholder: "パスワードを入力してください",
      confirmPassword: "パスワード確認",
      confirmPasswordPlaceholder: "パスワードを再度入力してください",
      language: "言語",
      languagePlaceholder: "言語を選択してください",
      signupButton: "会員登録",
      signupLoading: "登録中...",
      loginLink: "すでにアカウントをお持ちですか？",
      loginButton: "ログイン",
      errors: {
        allFieldsRequired: "すべてのフィールドを入力してください",
        passwordMismatch: "パスワードが一致しません",
        passwordTooShort: "パスワードは8文字以上である必要があります",
        signupFailed: "会員登録に失敗しました",
      },
    },
    home: {
      greeting: "こんにちは！",
      welcomeMessage: "洪吉童教授をお手伝いするAI Tutorです",
      homeTitle: "ホーム",
      uploadFile: "ファイルをアップロード",
      emptyState: {
        title: "講義動画をアップロードしてください",
        description:
          "ファイルをドラッグ＆ドロップするか、クリックして講義動画をアップロードできます！",
      },
      sidebar: {
        home: "ホーム",
        courses: "講義科目",
        logout: "ログアウト",
      },
      content: {
        translation: "翻訳版",
        summary: "要約",
        quiz: "クイズ",
        advanced: "深化",
        number: "番号",
        back: "戻る",
        summaryContent: "講義録音の要約がここに表示されます。",
        quizContent: "クイズの内容がここに表示されます。",
        advancedContent: "深化の内容がここに表示されます。",
        quizNumber: "クイズ番号",
        questionCount: "問題数",
        difficulty: "難易度",
        createdAt: "作成日",
        download: "ダウンロード",
        delete: "削除",
        createQuiz: "クイズ作成",
        quizGenerationComplete: "クイズ生成完了",
        select: "選択",
        problem: "問題",
        answer: "答え",
        questionType: "問題タイプ",
        generatePDF: "PDF生成",
        showAnswer: "答えを表示",
        hideAnswer: "答えを非表示",
        maxQuestions: "最大",
        questions: "問",
        difficultyHigh: "高",
        difficultyMedium: "中",
        difficultyLow: "低",
        questionTypeShortAnswer: "記述式",
        questionTypeTrueFalse: "○×",
        questionTypeMultipleChoice: "選択式",
        generateQuiz: "問題用紙生成",
      },
      uploadModal: {
        fileInfo: "ファイル情報",
        classTitle: "授業タイトル入力",
        cancel: "キャンセル",
        confirm: "確認",
      },
    },
  },
  vi: {
    intro: [
      "Bước 1: Tải lên các bài giảng bạn không hiểu",
      "Bước 2: Xem và học từ bản tóm tắt bài giảng được dịch sang ngôn ngữ mẹ đẻ của bạn",
      "Bước 3: Xem và học từ các câu hỏi được tạo ra",
      "Bước 4: Hãy thử học từ nội dung nâng cao bao gồm các khía cạnh sâu sắc của bài giảng",
      "Chúng ta hãy cùng học với Orbit nhé?",
    ],
    title: "Orbit",
    signup: {
      title: "Bắt đầu với Orbit AI",
      name: "Tên",
      namePlaceholder: "Nhập tên của bạn",
      email: "Email",
      emailPlaceholder: "Nhập email của bạn",
      password: "Mật khẩu",
      passwordPlaceholder: "Nhập mật khẩu của bạn",
      confirmPassword: "Xác nhận mật khẩu",
      confirmPasswordPlaceholder: "Nhập lại mật khẩu của bạn",
      language: "Ngôn ngữ",
      languagePlaceholder: "Chọn ngôn ngữ",
      signupButton: "Đăng ký",
      signupLoading: "Đang đăng ký...",
      loginLink: "Đã có tài khoản?",
      loginButton: "Đăng nhập",
      errors: {
        allFieldsRequired: "Vui lòng điền tất cả các trường",
        passwordMismatch: "Mật khẩu không khớp",
        passwordTooShort: "Mật khẩu phải có ít nhất 8 ký tự",
        signupFailed: "Đăng ký thất bại",
      },
    },
    home: {
      greeting: "Xin chào!",
      welcomeMessage: "Tôi là AI Tutor để giúp Giáo sư Hong Gil-dong",
      homeTitle: "Trang chủ",
      uploadFile: "Tải lên tệp",
      emptyState: {
        title: "Tải lên video bài giảng của bạn",
        description:
          "Kéo thả tệp hoặc nhấp để tải lên video bài giảng của bạn!",
      },
      sidebar: {
        home: "Trang chủ",
        courses: "Môn học",
        logout: "Đăng xuất",
      },
      content: {
        translation: "Bản dịch",
        summary: "Tóm tắt",
        quiz: "Câu đố",
        advanced: "Nâng cao",
        number: "Số",
        back: "Quay lại",
        summaryContent: "Tóm tắt của bản ghi bài giảng sẽ được hiển thị ở đây.",
        quizContent: "Nội dung câu đố sẽ được hiển thị ở đây.",
        advancedContent: "Nội dung nâng cao sẽ được hiển thị ở đây.",
        quizNumber: "Số câu đố",
        questionCount: "Số câu hỏi",
        difficulty: "Độ khó",
        createdAt: "Ngày tạo",
        download: "Tải xuống",
        delete: "Xóa",
        createQuiz: "Tạo câu đố",
        quizGenerationComplete: "Hoàn thành tạo câu đố",
        select: "Chọn",
        problem: "Câu hỏi",
        answer: "Đáp án",
        questionType: "Loại câu hỏi",
        generatePDF: "Tạo PDF",
        showAnswer: "Hiển thị đáp án",
        hideAnswer: "Ẩn đáp án",
        maxQuestions: "Tối đa",
        questions: "câu",
        difficultyHigh: "Cao",
        difficultyMedium: "Trung bình",
        difficultyLow: "Thấp",
        questionTypeShortAnswer: "Tự luận",
        questionTypeTrueFalse: "Đúng/Sai",
        questionTypeMultipleChoice: "Trắc nghiệm",
        generateQuiz: "Tạo đề thi",
      },
      uploadModal: {
        fileInfo: "Thông tin tệp",
        classTitle: "Nhập tiêu đề lớp học",
        cancel: "Hủy",
        confirm: "Xác nhận",
      },
    },
  },
  mn: {
    intro: [
      "1-р алхам: Ойлгохгүй лекцээ байршуулна уу",
      "2-р алхам: Эх хэлээр орчуулсан хичээлийн хураангуйг харж суралцана",
      "3-р алхам: Үүссэн асуудлуудыг харж суралцана уу",
      "4-р алхам: Хичээлийн гүнзгий талуудыг хамарсан дэвшилтэт агуулгаас ч суралцана уу",
      "Orbit-тэй хамт суралцъя уу?",
    ],
    title: "Orbit",
    signup: {
      title: "Orbit AI-ээр эхлэх",
      name: "Нэр",
      namePlaceholder: "Нэрээ оруулна уу",
      email: "Имэйл",
      emailPlaceholder: "Имэйлээ оруулна уу",
      password: "Нууц үг",
      passwordPlaceholder: "Нууц үгээ оруулна уу",
      confirmPassword: "Нууц үг баталгаажуулах",
      confirmPasswordPlaceholder: "Нууц үгээ дахин оруулна уу",
      language: "Хэл",
      languagePlaceholder: "Хэл сонгох",
      signupButton: "Бүртгүүлэх",
      signupLoading: "Бүртгүүлж байна...",
      loginLink: "Аль хэдийн бүртгэлтэй юу?",
      loginButton: "Нэвтрэх",
      errors: {
        allFieldsRequired: "Бүх талбарыг бөглөнө үү",
        passwordMismatch: "Нууц үг тохирохгүй байна",
        passwordTooShort: "Нууц үг дор хаяж 8 тэмдэгт байх ёстой",
        signupFailed: "Бүртгүүлэх амжилтгүй боллоо",
      },
    },
    home: {
      greeting: "Сайн уу!",
      welcomeMessage: "Би Хон Гиль-дон профессорт туслах AI багш байна",
      homeTitle: "Нүүр",
      uploadFile: "Файл байршуулах",
      emptyState: {
        title: "Лекцийн видеогоо байршуулна уу",
        description:
          "Файлуудыг чирж эсвэл дарж лекцийн видеогоо байршуулж болно!",
      },
      sidebar: {
        home: "Нүүр",
        courses: "Хичээлийн сэдвүүд",
        logout: "Гарах",
      },
      content: {
        translation: "Орчуулга",
        summary: "Хураангуй",
        quiz: "Асуулт",
        advanced: "Дэвшилтэт",
        number: "Дугаар",
        back: "Буцах",
        summaryContent: "Лекцийн бичлэгийн хураангуйг энд харуулах болно.",
        quizContent: "Асуултын агуулгыг энд харуулах болно.",
        advancedContent: "Дэвшилтэт агуулгыг энд харуулах болно.",
        quizNumber: "Асуултын дугаар",
        questionCount: "Асуултын тоо",
        difficulty: "Хүндрэл",
        createdAt: "Үүсгэсэн огноо",
        download: "Татах",
        delete: "Устгах",
        createQuiz: "Асуулт үүсгэх",
        quizGenerationComplete: "Асуулт үүсгэх дууссан",
        select: "Сонгох",
        problem: "Асуудал",
        answer: "Хариулт",
        questionType: "Асуултын төрөл",
        generatePDF: "PDF үүсгэх",
        showAnswer: "Хариулт харуулах",
        hideAnswer: "Хариулт нуух",
        maxQuestions: "Хамгийн ихдээ",
        questions: "асуулт",
        difficultyHigh: "Өндөр",
        difficultyMedium: "Дунд",
        difficultyLow: "Бага",
        questionTypeShortAnswer: "Богино хариулт",
        questionTypeTrueFalse: "Тийм/Үгүй",
        questionTypeMultipleChoice: "Олон сонголт",
        generateQuiz: "Асуултын хуудас үүсгэх",
      },
      uploadModal: {
        fileInfo: "Файлын мэдээлэл",
        classTitle: "Хичээлийн гарчиг оруулах",
        cancel: "Цуцлах",
        confirm: "Баталгаажуулах",
      },
    },
  },
};
